### ISSUE TITLE
No Eve history for Aqara Temp/Humidity/Pressure sensor

### ISSUE THREAD

**Issue by crazykiwi2003** [ebaauw/homebridge-deconz#44] opened 2022-05-03 09:33 UTC
Hello,

yesterday I set up a new homebridge instance and used homebridge-Deconz the first time. Everything works so far, but I cannot see the history for my Aqara sensors in Eve app, which is an essential feature for me. Is there a way to activate it?

Best regards

**Comment by ebaauw** [comment] 2022-05-04 21:55
Does Eve show empty history, or no history at all?

**Comment by crazykiwi2003** [comment] 2022-05-04 22:28
There is no history at all (not empty)

**Comment by ebaauw** [comment] 2022-05-05 05:50
Could you please attach the dump file, and indicate which sensors this concerns?  When setting _Log Level_ of the sensor accessory to 2, do you see any debug messages for the history entries?  New entries should be created every 10 minutes, and there should also be messages when Eve reads the history.

Have you tried Eve on another Apple device?

**Comment by crazykiwi2003** [comment] 2022-05-05 07:06
Sorry, but how to obtain the dump file? I cannot see any option for download in the plug-in settings view…

**Comment by ebaauw** [comment] 2022-05-05 16:54
It’s in the Homebridge user directory (same as config.json).  Homebridge deCONZ writes a log message when it creates the file, with the full path name.

**Comment by crazykiwi2003** [comment] 2022-05-05 20:31
Thanks a lot. Attached is what I found in the home bridge user dir.
The sensors concerned are all named "Multisensor*" and debug level is 2.
I cannot see any history related messages in the log. 
BTW, using 3 Apple devices here.
[homebridge.log](https://github.com/ebaauw/homebridge-deconz/files/8635873/homebridge.log)
[homebridge-deconz.json.gz](https://github.com/ebaauw/homebridge-deconz/files/8635883/homebridge-deconz.json.gz)

**Comment by ebaauw** [comment] 2022-05-06 07:49
I don't see anything wrong in the dump file.  Do you enable `DEBUG` under _Environment Variables_ in the Homebridge settings?  Without that, debug messages aren't logged.  Also, could you set `--trace-warnings` under `NODE_OPTIONS`?  I'm not too happy about this message, and want to see what causes it:
```
(node:6015) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 initialised listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6015) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit
```

> There is no history at all (not empty)

In the room view, do you see the arrow next to temperature, humidity and air pressure values, that you can drop down to see the (empty) history?  Or is the arrow missing?

**Comment by Monofin** [comment] 2022-05-10 21:08
Hi there: Second example of this here.
Only seems to apply to recently added (or deleted-then added) devices.
Doing some debug I discovered that the devices that lack history do not expose the custom service that carries the history service to HomeKit - Discovered this using the HAA app on my mobile.

I have three identical (Multi) sensors, all the same revision and firmware, one was added a few decent revisions ago, and the other two were deleted (and were showing history then), then re-added - at that point the history service stopped being exposed by those devices - that appears to be the only issue.
(I've tried scrubbing all the history files and restarting as well ;-)

This looks like something recent, any possibility its a DDF transition issue in deconz??

**Comment by Monofin** [comment] 2022-05-10 21:13
Hi there:

> (node:6015) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 initialised listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:6015) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Gateway]. Use emitter.setMaxListeners() to increase limit

That particular message seems to be a quirk of some older plugins (Risco Local Platform is one, I use that) that keeps adding listeners to the same EventEmitter - (it seems to be a 'fan out' design pattern issue), but the warning is *usually (caveats apply) indicative of poor performance coding, but not functional issues.

**Comment by crazykiwi2003** [comment] 2022-05-13 11:23
Now the plugin is crashing directly after startup with following errors:

`[13/05/2022, 13:10:40] [deCONZ] Phoscon-GW-neu: Multisensor11: add accessory
[13/05/2022, 13:10:40] [deCONZ] Multisensor11: LUMI lumi.weather v20161129 (3 resources)
Error: listen EADDRINUSE: address already in use :::58246
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:332:21)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:18)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
[13/05/2022, 13:10:42] [deCONZ] Child bridge process ended`


and


`[13/05/2022, 12:43:40] [deCONZ] created debug dump file /var/lib/homebridge/homebridge-deconz.json.gz

/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzPlatform.js:74
            '%s: request %d: %s %s', error.request.name,
                                                   ^
TypeError: Cannot read properties of undefined (reading 'name')
    at Discovery.<anonymous> (/usr/local/lib/node_modules/homebridge-deconz/lib/DeconzPlatform.js:74:52)
    at Discovery.emit (node:events:520:28)
    at /usr/local/lib/node_modules/homebridge-deconz/lib/Deconz/Discovery.js:159:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[13/05/2022, 12:43:43] [deCONZ] Child bridge process ended`

Any idea?

[homebridge-deconz.json.gz](https://github.com/ebaauw/homebridge-deconz/files/8686600/homebridge-deconz.json.gz)

**Comment by ebaauw** [comment] 2022-05-14 07:50
> Error: listen EADDRINUSE: address already in use :::58246

This is a NodeJS error that it cannot open the port for Homebridge's HAP server. because another process is already using that port.  Nothing to do with any plugin.  Most likely, you're already running Homebridge and are trying to start it again.

> TypeError: Cannot read properties of undefined (reading 'name')

That's a bug in Homebridge deCONZ' error handling alright.  Not exactly sure what the original error here is, though.

**Comment by ebaauw** [comment] 2022-05-14 08:53
@crazykiwi2003 thanks for the logs, this is the info I needed:
```
[12/05/2022, 17:32:36] [deCONZ] Phoscon-GW-neu: Multisensor3: add accessory
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: LUMI lumi.weather v20191205 (3 resources)
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: 3 resources: /sensors/10, /sensors/11, /sensors/12
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: /sensors/10: capabilities: {}
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: /sensors/10: params: {"primaryService":true,"serviceName":"Humidity"}
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: /sensors/11: capabilities: {}
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: /sensors/11: params: {"serviceName":"Temperature"}
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: /sensors/12: capabilities: {}
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: /sensors/12: params: {"serviceName":"AirPressure"}
[12/05/2022, 17:32:36] [deCONZ] Multisensor3 Settings: settings: {"name":"Multisensor3 Settings","subtype":"00158D0006B89B57","resource":"/sensors/10, /sensors/11, /sensors/12","expose":true,"logLevel":2}
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: subscribe to /sensors/10
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: subscribe to /sensors/11
[12/05/2022, 17:32:36] [deCONZ] Multisensor3: subscribe to /sensors/12
```
Homebridge deCONZ marks the ZHAHumidity `sensors` resource as the "primary" resource instead of the ZHATemperature resource.  Probably because the ZHAHumidity has a lower resource ID.json.  The history is exposed oblt when the ZHATemperature is marked as the "primary" resource.

**Comment by ebaauw** [comment] 2022-05-14 09:27
Could you try v0.0.16?

**Comment by crazykiwi2003** [comment] 2022-05-14 09:32
Great, works now! :-))
Many, many thanks!
Have a nice weekend

**Closed** 2022-05-14 09:36 UTC
Labels: bug

**Comment by Monofin** [comment] 2022-05-14 16:40
Confirmed working on 0.0.16
Thanks so much!
