### ISSUE TITLE
 Phoscon-GW: warning: request 146: /lights/12/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.

### ISSUE THREAD

**Issue by axelweichert** [ebaauw/homebridge-deconz#95] opened 2023-01-23 08:15 UTC
Since the Update to 0.1.1 i receive the following Error Messages on my Homebridge.

Homebridge Version: 1.6.0
Node js: v18.13.0

ConeBee II Version: 2.20.01 / 19.9.2022
ConBee Firmware: 26780700

All devices are controlable with Hue Essentials and no problems are shown there.

Here are the error messages:

[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: request 146: PUT /lights/12/state {"ct":276}
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: warning: request 146: /lights/12/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: request 147: PUT /lights/15/state {"ct":238}
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: warning: request 147: /lights/15/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: request 148: PUT /lights/16/state {"ct":310}
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: warning: request 148: /lights/16/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: request 149: PUT /lights/18/state {"ct":276}
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: warning: request 149: /lights/18/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: request 150: PUT /lights/22/state {"ct":276}
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: warning: request 150: /lights/22/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: request 151: PUT /lights/24/state {"ct":238}
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: warning: request 151: /lights/24/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: request 152: PUT /lights/25/state {"ct":209}
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: warning: request 152: /lights/25/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: request 153: PUT /lights/26/state {"ct":209}
[23/01/2023, 09:11:47] [deCONZ] Phoscon-GW: warning: request 153: /lights/26/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 154: PUT /lights/27/state {"ct":209}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 154: /lights/27/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 155: PUT /lights/28/state {"ct":238}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 155: /lights/28/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 156: PUT /lights/29/state {"ct":209}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 156: /lights/29/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 157: PUT /lights/30/state {"ct":209}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 157: /lights/30/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 158: PUT /lights/34/state {"ct":209}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 158: /lights/34/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 159: PUT /lights/35/state {"ct":209}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 159: /lights/35/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 160: PUT /lights/40/state {"ct":238}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 160: /lights/40/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 161: PUT /lights/41/state {"ct":238}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 161: /lights/41/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 162: PUT /lights/42/state {"ct":276}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 162: /lights/42/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 163: PUT /lights/50/state {"ct":209}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 163: /lights/50/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 164: PUT /lights/51/state {"ct":238}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 164: /lights/51/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 165: PUT /lights/60/state {"ct":276}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 165: /lights/60/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: request 166: PUT /lights/61/state {"ct":209}
[23/01/2023, 09:11:48] [deCONZ] Phoscon-GW: warning: request 166: /lights/61/state/ct: api error 201: parameter, ct, is not modifiable. Device is set to off.

**Comment by Monofin** [comment] 2023-01-23 11:10
Confirmed in v0.1.0 and v0.1.1 :

Repeated log messages to be associated (in my case) with the update of colour temperature by HomeKit when using the adaptive lighting, but no exclusively to it.

Can also prompt a slightly different warning for colour changes when in the off state, modifying xy:
[23/01/2023, 11:04:15] [deCONZ] xxxxxx: warning: request 344: /lights/2/state/xy: api error 201: parameter, xy, is not modifiable. Device is set to off.

Modifying the value of colour temperature/colour when the unit is set to off seems to be part of the behaviour of HomeKit, so that when the device is set to on, it takes on the colour/colour temperature that has been set - this is confirmed by the behaviour of the Home app's 'tell-tale' on the device settings, which changes its colour even when the device is off.

The result of turning the device off at the Home app, changing the colour temp or colour, then turning it on at the Home app is that the application's represented colour does not match the bulb's actual colour.

Hope some of that helps!

**Comment by axelweichert** [comment] 2023-01-23 13:41
Thank you. Helps to understand. Maybe it will be fixed in the next release?

**Comment by ebaauw** [comment] 2023-01-23 15:53
Damn, I was preparing for deCONZ v2.20, but that version crashes on my production installation, so I didn’t finish it.

Since the latest ZCL version, Zigbee lights might actually accept _Level Control_ and _Color Control_ commands while off, depending on a setting (per cluster).  Notably, the Zigbee 3 Hue lights support this.  deCONZ v2.20 and later support these settings, and will no longer return the warning when the setting is active.  Homebridge deCONZ will enable the settings, especially for adaptive lighting, but should still check whether the light is on for lights that don’t support the setting (and ignore the commands while off).

**Comment by Monofin** [comment] 2023-01-23 15:59
Ah - That makes a lot of sense, and explains the behaviour: anything I can do to help in the meantime?

**Comment by ebaauw** [comment] 2023-01-23 19:23
Quick fix in v0.1.2.

**Comment by axelweichert** [comment] 2023-01-23 19:36
Thanks a lot, that helped for the moment. :-)

**Comment by Monofin** [comment] 2023-01-24 10:34
Tested as resolving both issues above, as of v0.1.2 - thanks for the quick update!

**Closed** 2023-01-24 11:22 UTC
